services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: axa_admin
      POSTGRES_PASSWORD: Passer@123
      POSTGRES_DB: axa_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - axa-network

  app:
    # On récupère l'image que vous venez de publier
    image: 20188783/api-axa-cnaas:latest
    container_name: api-axa-cnaas
    depends_on:
      - db
    ports:
      - "8082:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/axa_db
      SPRING_DATASOURCE_USERNAME: axa_admin
      SPRING_DATASOURCE_PASSWORD: Passer@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - axa-network
  frontend-axa-cnaas:
    image: 20188783/frontend-axa-cnaas:latest
    container_name: frontend-axa-cnaas
    ports:
      - "80:82"
    depends_on:
      - app
    restart: always
    networks:
      - axa-network
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - axa-network

networks:
  axa-network:

volumes:
  pgdata: