version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: axa_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: axa_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axa_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: 20188783/api-axa-cnaas:latest
    container_name: api-axa-cnaas
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/axa_db
      SPRING_DATASOURCE_USERNAME: axa_admin
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata: