services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin@axa.sn
      POSTGRES_PASSWORD: Passer@123
      POSTGRES_DB: axa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    # On récupère l'image que vous venez de publier
    image: 20188783/api-axa-cnaas:latest
    container_name: api-axa-cnaas
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/axa_db
      SPRING_DATASOURCE_USERNAME: admin@axa.sn
      SPRING_DATASOURCE_PASSWORD: Passer@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata: