name: deploy api
on: [push]
jobs:
  generate-image:
    name: generate image
    runs-on: self-hosted
    steps:
      - name: clone le repertoire
        uses: actions/checkout@master
      - name: setup java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Give permission to mvnw
        run: chmod +x mvnw
      - name: generate and push
        run: |
          ./mvnw clean package spring-boot:build-image \
          -Ddocker.publishRegistry.username=${{ secrets.DOCKER_USERNAME }} \
          -Ddocker.publishRegistry.password=${{ secrets.DOCKER_PASSWORD }} \
          -Dspring-boot.build-image.publish=true \
          -Dmaven.test.skip=true
      - name: Deploy
        run: |
          cd /opt/axa-cnaas
          docker compose pull
          docker compose down -v
          docker compose up -d



