name: AXA CNAAS CI/CD

on:
  push:
    branches:
      - main
      - dev

env:
  IMAGE_NAME: 20188783/api-axa-cnaas

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Set tag (dev ou prod)
      - name: Set image tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          fi

      # 4️⃣ Build image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # 5️⃣ Push image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      # 6️⃣ Deploy (uniquement main → prod)
      - name: Deploy with Docker Compose
        if: github.ref_name == 'main'
        run: |
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          docker pull $IMAGE_NAME:prod
          docker compose -f docker-compose.yml up -d --remove-orphans